#!/bin/bash
# Source: https://stackoverflow.com/a/54595564

BUILD_ARCH= {DOCKERFILE_PATH}

[ "${BUILD_ARCH}" != "armhf" ] && \
    { echo 'qemu-user-static: Registration not required for current arch'; exit 0; }

docker run --rm --privileged multiarch/qemu-user-static:register --reset